### ISSUE TITLE
Provide a license file (e.g. MIT)

### ISSUE THREAD

**Issue by sunweaver** [tim-smart/node-redis#2]
Hi Tim,

I am currently preparing Etherpad-Lite for Debian and your Node.js module is a required dependency for that.

Unfortunately, you have not published node-redis under some specific license. May I ask you to choose a license and add that to your project either at the end of your README(.md) file or as a separate file named LICENSE? 

For orientation: Most projects I am currently packaging [1] use the MIT license. But BSD-3-clause, Apache-2.0 or some other license also works well. Please do not publish your code under one of the GPL licenses as that will give problems with projects that already depend on your code... (it would be like forcing them into a rewrite of node-redis).

[1] http://qa.debian.org/developer.php?login=sunweaver@debian.org
[2] https://github.com/visionmedia/commander.js/#license

**Comment by sunweaver** [comment]
Forgot to sign the above text with my name...

Greets+Thanks!
Mike (sunweaver@debian.org)

**Comment by tim-smart** [comment]
Thanks for the heads up. Hope the project is useful!
